### ISSUE TITLE
[问题]签到报错

### ISSUE THREAD

**Issue by JinShichang** [forchannot/LittlePaimon-plugin-Captcha#3]
![QQ截图20231201110113](https://github.com/forchannot/LittlePaimon-plugin-Captcha/assets/11838132/26d2fe6d-69f9-4eb9-b2e5-96e7028aad43)

**Comment by forchannot** [comment]
已经更新了

**Comment by JinShichang** [comment]
> 已经更新了

![QQ截图20231201111106](https://github.com/forchannot/LittlePaimon-plugin-Captcha/assets/11838132/7bc8a5f2-425e-47dc-a04b-00d849d56094)
看到了 但好像还是不行

**Comment by forchannot** [comment]
需要更新小派蒙本体

**Comment by JinShichang** [comment]
> 需要更新小派蒙本体

已解决 感谢！
